export * from './character.model'
export * from './episode.model'
export * from './location.model'
export * from './characterepisode.model'
export * from './characterorigin.model'
export * from './characterlocation.model'